In [ ]:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [37]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object=list_)

In [38]:
#lsit_ is a python list which can hold elements of diff data type here it is string
#array_list is a numpy array list

['1' '2' '3' '4' '5']


In [46]:
print("Data type of list_:", type(list_))
print("Data type of array_list:", array_list.dtype)

Data type of list_: <class 'list'>
Data type of array_list: <U1


In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [49]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [51]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
Q3. Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [52]:
array_list = np.array(object = list_, dtype = int)

In [59]:
print(array_list)

[1 2 3 4 5]


In [54]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [55]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [73]:
#Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
#Will there be any difference in the data type of the elements present in both the variables, list_ and
#arra_list? If so then print the data types of each and every element present in both the variables, list_
#and arra_list.
#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [74]:
for i in array_list:
    print(i.dtype)

int64
int64
int64
int64
int64


In [75]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [ ]:
#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [66]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [72]:
print(num_array)

[[1 2 3]
 [4 5 6]]


In [71]:
print(num_array.size)

6


In [70]:
print(num_array.shape)

(2, 3)


In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [64]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [57]:
k=np.diag([5,5,5,5,5])

In [62]:
np.matrix(k)

matrix([[5, 0, 0, 0, 0],
        [0, 5, 0, 0, 0],
        [0, 0, 5, 0, 0],
        [0, 0, 0, 5, 0],
        [0, 0, 0, 0, 5]])